name = "liminal-chat-edge"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
DOMAIN_URL = "http://localhost:8766"
CORS_ALLOW_ORIGIN = "*"
CORS_ALLOW_HEADERS = "Last-Event-ID"
CORS_EXPOSE_HEADERS = "Last-Event-ID"

# For local development
[env.development]
[env.development.vars]
DOMAIN_URL = "http://localhost:8766"
CORS_ALLOW_ORIGIN = "*"
CORS_ALLOW_HEADERS = "Last-Event-ID"
CORS_EXPOSE_HEADERS = "Last-Event-ID"

# For production (update this when deploying)
[env.production]
[env.production.vars]
DOMAIN_URL = "https://your-domain-server.com"
CORS_ALLOW_ORIGIN = "*"
CORS_ALLOW_HEADERS = "Last-Event-ID"
CORS_EXPOSE_HEADERS = "Last-Event-ID"