name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Convex types (@liminal/api)
        working-directory: apps/liminal-api
        run: pnpm exec convex codegen

      - name: Lint
        run: |
          pnpm -F @liminal/chat lint
          pnpm -F web lint
          pnpm -F @liminal/api lint

      - name: Typecheck
        run: |
          pnpm -F @liminal/chat typecheck
          pnpm -F web typecheck
          pnpm -F @liminal/api typecheck

      - name: Build
        run: |
          pnpm -F @liminal/chat build
          pnpm -F web build
          pnpm -F @liminal/api build

      - name: Unit tests (@liminal/chat)
        run: pnpm -F @liminal/chat test -- --run --reporter=dot


