name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]

jobs:
  claude:
    if: |
      github.event.sender.type != 'Bot' && 
      !contains(github.event.sender.login, 'bot') &&
      !contains(github.event.sender.login, '[bot]') &&
      github.event.sender.login != 'coderabbitai' &&
      github.event.sender.login != 'cursor' && 
      github.event.sender.login != 'coderabbitai[bot]' &&
      !contains(github.event.sender.login, 'coderabbit') && (
        (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude-pr') && github.event.sender.login != 'coderabbitai' && !contains(github.event.sender.login, 'coderabbit')) ||
        (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude-pr') && github.event.sender.login != 'coderabbitai' && !contains(github.event.sender.login, 'coderabbit')) ||
        (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude-pr') || contains(github.event.issue.title, '@claude-pr')) && !contains(github.event.sender.login, 'coderabbit'))
      )
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
